/* Copyright (C) 2007 Global Graphics Software Ltd. All rights reserved. */
/* Global Graphics Software Ltd. Confidential Information. */
/*
 $HopeName: SWcustomer!src:icon.h(EBDSDK_P.1) $

 Defines the bitmap for the customer's icon

Log stripped */

/* The scriptworks icon in the About dialog box. */

/* XPM */
static char *apzbSmallScriptWorksXPM[] = {
"54 54 5 1 0 0",
" 	s iconColor2	m white	c white",
".	c #7D7DFFFFD1D1",
"X	c #BABAE8E8E8E8",
"o	c #1919B2B2B2B2",
"O	s selectColor	m white	c #737373737373",
"                                                      ",
"..................................................... ",
".                                                   . ",
".                                                   . ",
".     .         ..          ..          .           . ",
".    .            .                    ......       . ",
".  ......      ........     .......        .        . ",
".    .           .....        ......       ......   . ",
".  .....           .                           .    . ",
".   .....        .......      .........      .....  . ",
".    .             .  ..          ....           .  . ",
".  .....           ..   ..                          . ",
".  .......     ......     ..    ..........       .  . ",
".  ...             ..       ..       .....          . ",
".                   .         ..                    . ",
".  ....            ...          .     .....         . ",
".  ........    .......          . ..............    . ",
".  .....           ...           .  ..............  . ",
".  ..                .           .        ......    . ",
".                    .           .                  . ",
".  ..                 .           .         .....   . ",
".  ......          ....           .       ........  . ",
".  .........    .......            .    ..........  . ",
".  ......         .....            .    ..........  . ",
".  ....              ..            .        ......  . ",
".  .                   .            .           ..  . ",
".                      .            .               . ",
".  .                   .            .               . ",
".  ...                 .             .              . ",
".  ......              ..            .              . ",
".  ........        ......             .          .  . ",
".  ..........   ...........           ..       ...  . ",
".  ........       ..............      .....  .....  . ",
".  ......            ................  ...........  . ",
".  ...                 ...........................  . ",
".  .                     .........................  . ",
".                          Xoooooooo..............  . ",
".                  XXXXXXXXXXXooooooo.............  . ",
".                  XXXXXXXXXXXXXoooooo............  . ",
".                   XXXXXXXXXXXoooooooo...........  . ",
".  ..               XXXXXXXXXooooooooooo..........  . ",
".  ....              XXXXXXoooooooooooooo.........  . ",
".  ......            XXXXooooooooooooooooo........  . ",
".  .......            Xoooooooooooooooooooo.......  . ",
".  .........         .oooooooooooooooo............  . ",
".  ...........     ....ooooo......................  . ",
".  ............. .................................  . ",
".  ............   ................................  . ",
".  ..........       ..............................  . ",
".  ........           ............................  . ",
".  ......               ..........................  . ",
".                                                   . ",
".                                                   . ",
"..................................................... "
};

char ** ppzbSmallScriptWorksXPM = apzbSmallScriptWorksXPM;


/* Icons handed to the window manager */
#if defined(AII)

/* XPM */
static char * apzbCustomIconXPM[] = {
"32 32 33 1",
" 	c #FFFFFFFFFFFF",
".	c #CCCCBFBFFFFF",
"X	c #CCCC00005555",
"o	c #FFFFDFDFFFFF",
"O	c #CCCCFFFFFFFF",
"+	c #00009F9FFFFF",
"@	c #9999DFDFFFFF",
"#	c #FFFF9F9FAAAA",
"$	c #00009F9FAAAA",
"%	c #CCCC0000AAAA",
"&	c #99990000AAAA",
"*	c #0000BFBFFFFF",
"=	c #0000BFBFAAAA",
"-	c #CCCCDFDFFFFF",
";	c #66666060AAAA",
":	c #666640400000",
"?	c #000000000000",
">	c #999980805555",
",	c #CCCC2020AAAA",
"<	c #FFFF40405555",
"1	c #CCCC8080FFFF",
"2	c #6666BFBFFFFF",
"3	c #333340405555",
"4	c #FFFFFFFFAAAA",
"5	c #99999F9F5555",
"6	c #666680805555",
"7	c #CCCCBFBFAAAA",
"8	c #666660605555",
"9	c #FFFFDFDF0000",
"0	c #FFFFFFFF0000",
"q	c #99999F9FAAAA",
"w	c #66668080AAAA",
"e	c #333360605555",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                  .XXo    O++@  ",
"                 #XXXX#  @$+$+O ",
"                 X%X&X%  *+=+*+ ",
"                 XXXXXX  +$+$+$-",
"                 X&XXX&  =+++=+ ",
"   ;:???????>    ,XXXX<  @$+$+@ ",
"  ????????????-    #1      @2   ",
"  ?????????????  ??????  ?????? ",
"  ????3>???????  ??????  ?????? ",
"  4     5??????  ??????  ?????? ",
"     6?????????  ??????  ?????? ",
" 7?????????????  ??????  ?????? ",
"8?????90???????  ??????  ?????? ",
"?????9090??????  ??????  ?????? ",
"?????0909??????  ??????  ?????? ",
"?????9090??????  ??????  ?????? ",
" ?????90???????  ??????  ?????? ",
" 7?????????????  ??????  ?????? ",
"   6????3qw>wqw  33e333  33e333 ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
#endif

#ifdef TRIPLE_I

/* XPM */
static char *apzbCustomIconXPM[] = {
"32 32 5 1",
"` c black",
"a c cyan ",
"b c magenta",
"c c white  ",
"d c yellow ",
"``````````c``````````c``````````",
"``````````c``````````c``````````",
"``````````c``````````c``````````",
"``````````c``````````c```acaa```",
"``````````c``````````c``acccaa``",
"``````````c``````````c``cccaaa``",
"``````````c``````````c``acaaaa``",
"``````````c``````````c``aaaaaa``",
"``````````c``````````c```aaaa```",
"``````````c``````````c``````````",
"``````````c``````````c``````````",
"``````````c``````````c``````````",
"```dcdd```c```bcbb```c``````````",
"``dccddd``c``bccbbb``c``````````",
"``dcdddd``c``bcbbbb``c``````````",
"``dddddd``c``bbbbbb``c``````````",
"``dddddd``c``bbbbbb``c``````````",
"```dddd```c```bbbb```c``````````",
"``````````c``````````c``````````",
"``````````c``````````c``````````",
"``````````c``````````c``````````",
"cccccccccccccccccccccccccccccccc",
"``````````c``````````c``````````",
"``````````c``````````c``````````",
"``````````c``````````c``````````",
"cc``````ccccc``````ccccc``````cc",
"ccc````ccccccc````ccccccc````ccc",
"ccc````ccccccc````ccccccc````ccc",
"ccc````ccccccc````ccccccc````ccc",
"cc``````ccccc``````ccccc``````cc",
"``````````c``````````c``````````",
"``````````c``````````c``````````"
};

#endif

#ifdef SEI
/* XPM */
static char *apzbCustomIconXPM[] = {
/* width height colors chars_per_pixels */
"32 32 2 1",
/* colors */
" 	s iconColor1	m black	c black",
".	s iconColor2	m white	c white",
/* pixels */
" . .                    . . . . ",
" .   .................   .   . .",
" . . . ..  ...  .. ..  .  ..  . ",
" .   . . .. . .. . . . ..   .  .",
" . . . . .. . .. . . . ... . . .",
" .   . ..  ...  .. ..        .  ",
" . . ......................  . .",
" .            .....             ",
" .   .   .     ... .... .. ..  .",
"            .  .. . .  . . .    ",
".  .  .  .     . .. . . . . .  .",
"             .. .. . . . . .    ",
".  .  .     .. . . . .         .",
"        .  ..  .. . .           ",
".          . .. . .    . .. . . ",
" .       .. . . . .   ... . .  .",
"  . .... . .. . .    ... ..  . .",
".         . . . .   .          .",
"  ... ..... . .    . .......  . ",
". .  .    . . .   . ..   . .   .",
"  . . ... . .    . .. .. .    . ",
"  . . . . . .   . .. .  . ..   .",
".             .. .              ",
"             ...              . ",
". .  . .. .  ..............   . ",
" . . . ..  . ..           . . . ",
" .   . ..    ..............  . .",
" . . . ..    ..           . .   ",
" .   . ..  . ..............  . .",
" . . .       ..   .   .   . . . ",
" .   ......................  . .",
" . .                        .   "};

#endif

#ifdef CORTRON

/* XPM */
static char *apzbCustomIconXPM[] = {
/* width height colors chars_per_pixels */
"32 32 178 2",
   "`` c black",
   "`a c #cec6de",
   "`b c #6b73b5",
   "`c c #f79c4a",
   "`d c #dede73",
   "`e c #7bad8c",
   "`f c #deada5",
   "`g c #d6b508",
   "`h c #7bd6ef",
   "`i c #9cdeff",
   "`j c #9c6318",
   "`k c #f7de7b",
   "`l c #d62194",
   "`m c #ce5a5a",
   "`n c #183142",
   "`o c #bd7b42",
   "`p c #de63a5",
   "`q c #10adef",
   "`r c #73ad73",
   "`s c #109cce",
   "`t c #c663b5",
   "`u c #9c9400",
   "`v c #add642",
   "`w c #e79429",
   "`x c #183131",
   "`y c #a52963",
   "`z c #a5a5d6",
   "`{ c #8cad7b",
   "`| c #ce217b",
   "`} c #52ada5",
   "`~ c #8c6b8c",
   "a` c #7b949c",
   "aa c #a57b94",
   "ab c #424a18",
   "ac c #5a6b6b",
   "ad c #84bdb5",
   "ae c #847b31",
   "af c #e77b4a",
   "ag c #6bce7b",
   "ah c #f77b9c",
   "ai c #b5e7ef",
   "aj c #8c949c",
   "ak c #d69c5a",
   "al c #291010",
   "am c #ce6b84",
   "an c #de0084",
   "ao c #6b636b",
   "ap c #efef08",
   "aq c #421018",
   "ar c #ded629",
   "as c #8c2939",
   "at c #a5bd4a",
   "au c #ce3984",
   "av c #d67bbd",
   "aw c #d6ef31",
   "ax c #9c5a31",
   "ay c #e75a5a",
   "az c #391029",
   "a{ c #a5ad8c",
   "a| c #f75a42",
   "a} c #7b5263",
   "a~ c #7b3942",
   "b` c #423142",
   "ba c #7b7331",
   "bb c #4abdff",
   "bc c #f75284",
   "bd c #8cd6d6",
   "be c #cec64a",
   "bf c #18b5de",
   "bg c #e7d652",
   "bh c #a59c5a",
   "bi c gray87",
   "bj c #f72163",
   "bk c #4a425a",
   "bl c #5a4a42",
   "bm c #5ab594",
   "bn c #423931",
   "bo c #a5c6de",
   "bp c #f7f708",
   "bq c #eff7ff",
   "br c #7b4252",
   "bs c #94d663",
   "bt c #6b7ba5",
   "bu c #f70084",
   "bv c #add66b",
   "bw c #f7ef4a",
   "bx c #9463bd",
   "by c #de5a5a",
   "bz c #f7bd08",
   "b{ c #393942",
   "b| c #a59421",
   "b} c #39a5b5",
   "b~ c #5a1831",
   "c` c #b57352",
   "ca c #e72184",
   "cb c #d6ce08",
   "cc c #b5add6",
   "cd c #006b73",
   "ce c #de217b",
   "cf c #e7de08",
   "cg c #08425a",
   "ch c #4a2942",
   "ci c #187ba5",
   "cj c #d6bd29",
   "ck c #081018",
   "cl c #dea5c6",
   "cm c #f77b4a",
   "cn c #d6de8c",
   "co c #189cb5",
   "cp c #5ab58c",
   "cq c gray55",
   "cr c #ef8ca5",
   "cs c #a59c94",
   "ct c #de9c94",
   "cu c #8c9cce",
   "cv c #293910",
   "cw c #f752ad",
   "cx c #10bdff",
   "cy c #6b5a29",
   "cz c #5ac6de",
   "c{ c #5a7339",
   "c| c #ad217b",
   "c} c #52adb5",
   "c~ c #f7bd84",
   "d` c #e7ef21",
   "da c #ef4294",
   "db c #4a8c8c",
   "dc c #31a5e7",
   "dd c #316363",
   "de c #6b214a",
   "df c #424200",
   "dg c white",
   "dh c #00c6ff",
   "di c #a5ad6b",
   "dj c #5273b5",
   "dk c #6b525a",
   "dl c #10c6e7",
   "dm c #dee7ef",
   "dn c #c6e7ff",
   "do c #adadb5",
   "dp c #4273a5",
   "dq c #1094a5",
   "dr c #dec6ce",
   "ds c #b5c621",
   "dt c #f75a63",
   "du c #7b6b10",
   "dv c #39739c",
   "dw c #7bbdd6",
   "dx c #ad5252",
   "dy c #deefde",
   "dz c #216b84",
   "d{ c #d6d6b5",
   "d| c #109494",
   "d} c #7b0842",
   "d~ c #422910",
   "e` c #ad3973",
   "ea c #b5dee7",
   "eb c #f72184",
   "ec c #9c0052",
   "ed c #10adf7",
   "ee c #d69c73",
   "ef c #5a4263",
   "eg c #d65284",
   "eh c #ef9c7b",
   "ei c #181018",
   "ej c #efbdde",
   "ek c #e75a84",
   "el c #294a5a",
   "em c #5a9cd6",
   "en c #6b6b31",
   "eo c #f7bd29",
   "ep c #de395a",
   "eq c #4aa5e7",
   "er c #a5295a",
   "es c #a59c42",
   "et c #f7e7ad",
   "eu c #deef52",
   "ev c #39c6f7",
"dgdgdgbqdydgdydgdydgdybqdgdgdgdgdydgdgdgdgdgdgdgdgdgdgdgdgdgdgdg",
"dgbucaebebbuebebebebbcbcahehc~c~c~c~`kbgbwbweod`bpcfcfatbf`q`qdc",
"dgcaebbubucaebcaebekcw`cc~ehc~c~`k`kbwbwbwcfbpbparbvbmcxbf`qbfev",
"dgcabucacaebdabcdaekdtam`odxbhbgbgbwbwd`d`d`bg`edlcxcxbfcxcxdcag",
"dgcaebcaebegepdxerbnazeieieibnbad`bwcfbwbseqbfdhcxedcxbfadbsbwd`",
"dgebcaaua~d~azei````````````eiabcjcfbgb}cxcxcxeddcczbsd`d`bpapbp",
"dgcacedeei``````````````````eiabdsbsdcdhcx`qbfczbsapbpd`d`cfaweo",
"dga~az````ei`````````````````xdvbfcxcxed`qbfbsapbpbpd`bpeod`eobp",
"dg`````````````````````xcgcdbfbfcxcxbfcxagarbpbpcfd`bpeobpeobpbw",
"dg````````````````dfeldqbfcxedcxedcxedbmbpapbpd`d`bpcfbpeoapeo`c",
"dg``````````eienc{d|bfcxcpagajbvbs`vbgd`d`bpd`bpcfeoeoeoeo`c`ccm",
"dg``````ckeld|bfdhcxdccxagadbs`veuaw`vd`eobpbpeobpbpbpeo`c`ccmdt",
"dg``ckcibfbfdcbfcxbfc}`{`vawawapbgbpawd`bpd`eocf`ceo`c`cdtdtdtca",
"dgcgbfbfagbv`vdsbsbs`ebvbpd`d`bwbpd`eobpd`eod`eoeoeocmcmdtaybucm",
"dg`s`qbmd`bpbpbpbpbpd`bpd`d`d`bpbwbwd`bgeoc~`cehdtehdtebcacacaca",
"dgcxbfbvbpcfapbpapbpbpbpawbparapcfeoeoeoeeafeeaybybjcabjbjbububu",
"dgembtcjcfbpbpcfbpcfbpapbwbgeoeobpbwbwbedieectaaamamegca`lcaauca",
"dg`|dt`wbpcfcfbpbpbpeod`dicnbvbea{etdmdwdc`ibdeddwea`tbx`tej`tbx",
"dgebbjeobpbpbpcfbpcfbpeo`da{agc}agdnbibobbaidn`h`i`aea`z`zdg`zcu",
"dgebcaa|bpbpcfbpeocfaeaea`bmdcdccxeadnczbbbqbq`h`ibq`i`h`idg`icz",
"dgcaebdtcfeobpbwesbncyabbt`}dzcg`ncubd`bcsccavememczbbdceqbdeqdc",
"dgcaebbuc~ahak`mazchazb~deasei``eidydmcsdmbqbqbuahdgejcwcrdgejeb",
"dgebcacacabce`blb`bn`xala~deaq``eiaoa}bk`~ct`pcacwejcrdacwdgdada",
"dgcaebebebe`b`chbnazb~brecbyaq````ei````cvaudabudaclcwebcwcrcwca",
"dgcacadaauchazcvazckde`ydtaybyax`jcsdodi`~crclcadacrcwcadaejcwbu",
"dgebcacab~eiaz`xeieia~`ybybjaf`wb|`fd{ct`fejclebcwclcwcwcwejcwca",
"dgcaebc|``az`xeialercabj`c`weoeobzetetet`kdrclebahdgej`pcrdgcrcw",
"dgeb`leieickeieid}ancabjcmcm`w`gcbet`kcjeeehehepamclcwcwcwejcwcw",
"dge`ei````ei`xefbxbx`bcuaebh`j`ubh`d`ddubhamc`b~e`crdacadaclebcw",
"dg````````el`sdlcxbfeqdj`ra}ckb{cqdmdrel`fdrbd``acbqclavejdgcrcw",
"dg``````el`sbfcxedcxdcdldpdbcv````bnb{eiddacdk``bnajegcaebejcwca",
"dg``eickcoedcxdcdhdcbfcxdbdb`xcveicvbneibnbnbn``cha}e`cacacwebeb"
};

#endif

#if defined(LDRRIP) || defined(LDRRIPSMP)

/* XPM */
static char *apzbCustomIconXPM[] = {
/* width height num_colors chars_per_pixel */
"85    67       16            1",
/* colors */
". c #25282f",
"# c #181c28",
"a c #1b4769",
"b c #002c5b",
"c c #86a7b6",
"d c #678aa3",
"e c #162e45",
"f c #657f90",
"g c #6f6752",
"h c #e1e4df",
"i c #a7c4cb",
"j c #0d121b",
"k c #4e708c",
"l c #374557",
"m c #a69367",
"n c #030304",
/* pixels */
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbabbbabaaaaaaaabaaaaaaaalalaaaababaeabaaaaaaaababbebbbbebebbbbbbebbebebebebbebebebee",
"bakalklkffkffkfkkddccccciiiiiddkllllllkkkfcccfllle..e..####.#.#.##.########jnnnnnnnjk",
"ballklkfkfffkdfdfccddccciiiicdfllllllllllfkdfkllll...#.#.#.#e#.....##e...##jjjjjnjj.d",
"bblllkkkfdffdfddcddcciciiiicdfkllllggmmmmkkffllll.e.#####..e#######ee..####jnjnnnjn#k",
"balkkkkffddcdfcccccccccciiccdkllllmmlllgfmgkgllll....###.###.#.##.#..#.###jnnjnnjnned",
"balkakfkdcccccdccdccciicicddkklllgge.lllllmmakll....##e#.##e####.##e.#####jnjnnnjnn.d",
"bblkkfkfccccccdiccciiiifcdcfkllllml.ee.lelkmfllle.e#######e###.#.#ee##j##jjnjnnnnjn.d",
"bafkfkddcccccdciciiiiiiffkkkglllgm#e..l.llllmgl...##.####e#########.#####jjnnnnnjnn#d",
"blkkkfdcciciiicciiiiicfdfgkgala.mgj....e..llgmg#e###j##########.####lj###jnnnnnnnnn.d",
"bakkfffccicciiiciiicccfffkellll.mgee##e..l..lgml####.#################jj#jjnnnnnnjn#k",
"bafffffccdfiiiiicccccdkfkllllllemg####....ell#mf################j###.j##jjnnnnnnnnn#d",
"baddkdcciicdciccfdccdfgklllgale.mge.e.e.#e#.e.emlj##j#############j#ejjjjjjnnnnnnnn#d",
"badffciiiicfffffkfcffllkllgall..mg##.l###.#..e#lm#####j###########e...##jjnnnnnnnnn#d",
"baddccciicdfffdfglkfllklllale..#mg###e#####.e..#mgjjj####j#####j#..#j##jjnnnnnnnnnn#k",
"bkdccciiicfffffgkkllllglllll.l##gmj###.#########.mjj#j##j###jj##j##jjjjjnjnnnnnnnnn#d",
"bkccciiicdffkgglkllglklalll.l..#.mn#j.e######.###ggjj##j#.#j###j#..jj#jnjnnnnnnnnnn#k",
"bacciiiicfklkklkkllallgmmmmmmmmmgmgl##j....#.#####mjjj##j.e##e...#jj#jnjjjjnnnnnnnn#d",
"bkiciiicdfklgllllllllmmgll....#.lmmmmmgl.j.l#####jggjj#.#.el..#l.jj#jjjjjjnnnnnnnnn#d",
"bkiciicdfklllllllllgmmlle....###ngln#ggmmggen####j.mjj#.##j#jjj#.jjjjnjnnjnnnnnnnnn#k",
"bkiiicccfklllllllllmgee.....#####ggjjjn#jlgmmge#jjjmmn#.#j#jjjjj#.#jnjjn#nnnnnnnnnn#d",
"bfiiiccfkllllllleemmel....###.##j#mj###j#jnjlgmmg#njm...jjjjj#jjj.#jjjnjnnjnnnnnnnn#d",
"bfiiccdkkllll.eel.mle.l..##.####jjm.j#j#jjjj#ln.mmg.gg.#jj#j#jj#jnjj#jnnnjnnnnnnnnn#k",
"bkiicdkklll..l.l..ml..e..e.e###j#jggnj#jj#jjll....gmmm.jjjjjjjjjnjjjjjnjjnnnnnnnnnn#d",
"bkccdfkllll.l.....ml#...e##.##.#jj.mn#jj#jj#.n#.ejnjlmmgjjjjjjjnjjjnnjnnnnnnnnnnnnn#d",
"bkdcdkklgl.e....##gm.########e#jjjjm.jj.jj..#####jjjjlmmmgnjjjjjjjnjjnnjnnnnnnnnnnn#d",
"baddfklllal..####e.hmn..#####.#jj#nggn#jjj.#nj.jjnjjjjm..mm.jnjjnnjnnjjnnnnnnnnnnnn#d",
"badfflll.#jjjjjjjjnjmgj##jj#jljjjjjgmn#jjj.#n#njnjjjjnggnj.mm.nnn#nnjnnnnnnnnnnnnnn#d",
"blfflgleeaeaaaaklkkk.mgjj#jj#j..#jjnm.jjjjj#gmhgnjnjnjnm.jjj.mm#njnjjnnnnnnnnnnnnnn#k",
"bakllkl#aakkddcciihhe.mmnjj#jjj#.jjnggnjjj..mhhmnnjjnjnggnjjjngmgnnnnnnnnnnnnnnnnnn#d",
"ballkle#akadddccihhhlj.mm#jjjjjj.jjnlm...l..mhhm.jnjnjj.mnnjnnn.mm.nnnnnnnnnnnnnnnn#d",
"bbllllljakkaaalklkkkejjjgmgjjjjn#.j##m..l.#jmhmgjjnjnjnjm.njn#jnn.mgnnnnnnnnnnnnnnn#f",
"ballll.#kdkejn#njjnnnjjjj.gm.nj#.#.jeggj#n#jnnjjjnjnj###lgnnjnnjnnnggj#nnnnnnnnnnnn.d",
"bbllle##kkdjnnjnjjeba##jjnjlhm.jn#baakckajn#eal.nnneeaakklejnnj.ba#elkkk#nnnnnnnnjn.k",
"bel.l##akdcaaalkljeakanjjjjkiimg.bakkdhmcf#jeccknjeaakkddccf#nnealaadkdcdennnnnnnnn.f",
"bb..ljaddccihhhhijekkbj#jnjkhi#gmifkbagmic#nacclneaakkkkkciicjneakkkkkdcccjnnnnnnnn.d",
"be.ee#lcciihhhhhcjekkb#jjjndhi#.lfmmgjnmmjnnlciknbafk.jnn#dihdjekkkbjnjkihknnnnnnnn#f",
"bb#...lkciidddckljakdajjjnndhh#bkkb#mmg.m##naciknakk#nnnjnjchhjekkajnnn#chcnnnnnnnn.d",
"be##..jndhijnnnn#nbddajjnnnchhjakkkkdcihicieaihgjkkajnjjnnnkhhlekkannnnjdhinnnnnjnn#f",
"bbj.####chi#j###.jadda#njnjdhinadddciiihhhhmghhd#kdajnnnnnnkhhebddannnnndhhnnnnnjjj.d",
"be###.##chh#j#jjjjbciknnnjjchdneeebllellfhmgmhhmjkdknnjjnjjkii#eddannnn.dhinnnnnnnn#f",
"be.#####ihi##jnnjn.cidnnjjeicknjnjnnnnnjdhhnahhmmcidennnnnecidnbdclnnn.mchijnnnnnnn.f",
"bel....jihcejjjjjnjfiiclekccdejjbkkejbakicmjlhhlnlihimg..accdbnacclnjgmndhcnnnnnnnn#d",
"bbjj.#jecid#njnnnjnjchhhhicdajjbdiihihihckgmliianngihhhhhhihmglgihmmggnndiknnnnnnnn.d",
"bejj##jjdckjnjnjnnnnjchhhidajjjnlihhhhhckjnggcdbnnneihhhhcmg#lgghigjnnnnkcknnnnnnnn#d",
"bbnjjjjjelbjnjnnnjnnnjgcfabjj#jnnjldidklnnn.mbe#nnnnjlcdf.#gnnnnll.nnnnn#ebnnnnnnnn#d",
"bjjj#j#jjnnnnjnjnjnjnjnnnnjnnj#nnnnnnnnjnnnnm.njnnnnnnnnnnnmjnnnnnnnnnnnnnnnnnnnnnn#d",
"bbjjjjjj#jjnnnnnjnnnnnnnnnjnjj#nnjnnnj#jnnjn.mgnnjnjnjjnnnnmnnnnnnnnnnnnnnnnnnnnnnn#k",
"benjjjjjjnnjnjnjnnnjnjnjjnnjjnn.#..jn#jjnnnnngmnnnnnnnjjnnnmjnnnnnnnnnnnnnnnnnnnnnn#d",
"bjjjjjnjjjnnjnnjnnnnnnnnn###jnjjjnn..jnnnnjnnnmgnnnnnnnnjnnmnjnnnnnnnnnnnnnnnnnnnnn#d",
"bbnnjnjjjnnjnnnnnnjnnnnnjjnnnj#.nnj.nnnnnnnnjnnmjnnnnnnnjnnm.nnnnnnnnnnnnnnnnnnnnnn#k",
"bjnjnjjjnjnnnnnnnnnnnnnjnnnnnnnnjjn.#nnnnjnjjnn.mnnnnnnnnnnmjnnnnnnnnnnnnnnnnnnnnnn#d",
"bbnjjnnnnjnjnnjnjnnnnnnnnnnnnnnnnnnj.jjjnnjjnnnnggnnnnnnnnnmnnnnjnnnnnnnnnnnnnnnnnn#d",
"bjnnnjjjnjnnnnnnnnnnnnnjnnnnnnnnnnnj.nnnnnjnnnnnnmgnnnnnnnnmnnnnnnnjnnnnnnnnnnnnnnn#d",
"b#jnjnnnnjnnnnnnnnnnnnjnnnnnnnnjnnnnjnnnnnnnnnnnnnm.nnnnnn#mnnnnnnnnnnnnnnnnnnnnnnn#d",
"bbnnnnjnjnnnnnnnnnnnnnnnnnnnnnnnnnnnj.jjnjjnnnnnnnnmmnnnnnmgnnnnnnnn#nnnnnnnnnnnnnn#k",
"bjnnjnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnj#jnnnnnnnnnnnnngmgnngmnnnnnnnnnnnnnnnnnnnnnnnn#d",
"b#nnnnnnjnnnnnnnnnnnnnnnnnnnnnnjjjnnjn.jnnnjnnnnnnnnn.ggmgnnnnnnnnnnnnnnnnnnnnnnnnn#d",
"b#nnnnnjnnnnnnnnnnnnnnnnnnnnnnnnnnnjnjnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn#d",
"b#nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn#d",
"b#nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnjjnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn#k",
"b#nnnnnjnnnnnnnnnnnnnnnnnnnnnnnnnnnnnjnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn#d",
"bbnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnjnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn#d",
"bjnnnnnnnnnnnnnnnnnnnnnnnnjnnnnnnnnnnn#nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn#d",
"b#nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn#d",
"b########################.###########.##.##########################################lc",
"bakdddddkdkdkdkdddkdkdddddkdkddkddkddddddddddfdkdfddkdfdkddfdfdfdddddfddfdkdddkdfddcc"
};

#endif /* LDRRIP and LDRRIPSMP */

#if defined(MORISAWA)

/* XPM */
static char *apzbCustomIconXPM[] = {
/* width height ncolors chars_per_pixel */
"32 32 20 1",
" 	c #A0A0A0A0A4A4",
".	c #808080808080",
"X	c #00009F9FAAAA",
"o	c #55559F9FAAAA",
"O	c #FFFFFFFFFFFF",
"+	c #2A2A3F3F5555",
"@	c #CCCCCCCCFFFF",
"#	c #55555F5FAAAA",
"$	c #AAAA9F9FAAAA",
"%	c #55553F3FAAAA",
"&	c #FFFFBFBFAAAA",
"*	c #FFFFBFBF5555",
"=	c #00007F7F5555",
"-	c #55557F7F5555",
";	c #FFFF9F9F0000",
":	c #AAAA9F9FFFFF",
"?	c #55559F9F5555",
">	c #D4D49F9F0000",
",	c #000000000000",
"<	c #55553F3F5555",
"                               .",
" XXXXXoOOOOOXXXXXoOOOOOOOOOOOOO+",
" XXXXXoOOOOOXXXXXoOOOOOOOOOOOOO+",
" XXXXXoOOOOOXXXXXoOOOOOOOOOOOOO+",
" XXXXXoOOOOOXXXXXoOOOOOOOOOOOOO+",
" XXXXXo@##@OXXXXXoOOOOOOOOOOOOO+",
" XXXXX$%%%%$XXXXXoOOOOOOOOOOOOO+",
" XXXXX#%%%%#XXXXXo&**&OOOOOOOOO+",
" XXXXX#%%%%#XXXX=-;;;;;*OOOOOOO+",
" XXXXX$%%%%$XXX==-;;;;;;;&OOOOO+",
" XXXXXo:##@OXX===-;;;;;;;;&OOOO+",
" XXXXXoOOOOOX====-;;;;;;;;;OOOO+",
" XXXXXoOOOOO=====-;;;;;;;;;&OOO+",
" XXXXXoOOOOO=====-*OO*;;;;;*OOO+",
" XXXXXoOOOOO=====?OOOO*;;;;;OOO+",
" XXXXXoOOOOO=====?OOOO&;;;;;OOO+",
" OOOOOOOOOOO>>>>>*OOOO*;;;;;OOO+",
" OOOOOOOOOOO*;;;;;*OO*;;;;;*OOO+",
" OOOOOOOOOOO&;;;;;;;;;;;;;;*&&&+",
" OOOOOOOOOOOO;;;;;;;;;;;;;;;;;;+",
" OOOOOOOOOOOO&;;;;;;;;;;;;;;;;;+",
" OOOOOOOOOOOOO&;;;;;;;;;;*;;;;;+",
" OOOOOOOOOOOOOOO*;;;;;;*&O&;;;;+",
" OOOOOOOOOOOOOOOOO&**&OOOOO****+",
" O,,,$O,OO,,$O$,,$O,,,$O,O,,,$O+",
" O,$$,$,O,$$,O,$$,O,$$,$,O,$$,O+",
" O,OO,$,O,$O$O,::,O,OO,$,O,OO,O+",
" O,$,$O,O$,,$O<%%,O,$,$O,O,$,$O+",
" O,$$,O,O$O$,O,::,O,$$,O,O,$OOO+",
" O,$O,O,O,$O,O,$O,O,$O,O,O,$OOO+",
" O,$O,O,O$,,$O,$O,O,$O,O,O,$OOO+",
".+++++++++++++++++++++++++++++++"};

#endif

#if defined(HARLQN) || defined(GENMPS) || defined(QA)


static char *apzbCustomIconXPM[] = {
"32 32 3 1",
"` c #19b2b2 m black  s  dark_color ",
"a c #7dffd1 m black  s  dark_color ",
"b c white   m white  s  light_color",
"abbbbbbbbbbbabbbbbbbbbbbbbbbbbbb",
"aaaaaaabbbbbaaababbbbbaaaaabbbbb",
"abbbbbbbbbbbabbaabbbbbbbbbbbbbbb",
"abaaaaabbbbbaabbbaabbbaaaaaaabbb",
"abaaabbbbbbbbabbbbbaabbbbbaaaabb",
"abbbbbbbbbbbbabbbbbbbabbbbbbbbbb",
"aaaaaaabbbbbaabbbbbbbabbbaaaaaaa",
"aaaabbbbbbbbbbabbbbbbbabbbbbbaaa",
"aabbbbbbbbbbbbabbbbbbbabbbbbbbbb",
"aaaabbbbbbbbbbabbbbbbbbabbbbbbaa",
"aaaaaaaabbbaaaabbbbbbbbabbbbaaaa",
"aaaaabbbbbbbbbbabbbbbbbabbbbaaaa",
"aaabbbbbbbbbbbbabbbbbbbbabbbbbbb",
"abbbbbbbbbbbbbbabbbbbbbbabbbbbbb",
"aaabbbbbbbbbbbbabbbbbbbbabbbbbbb",
"aaaaabbbbbbbbbbbabbbbbbbbabbbbbb",
"aaaaaaabbbbbbbaaaaabbbbbbabbbbbb",
"aaaaaaaaabbbaaaaaaaaaaaabbaaaabb",
"aaaaaaabbbbbbbaaaaaaaaabaaabaaaa",
"aaaabbbbbbbbbbbbbaaaaaaaaabbaaaa",
"aabbbbbbbbbbbbbbbbb``````aaaaaaa",
"abbbbbbbbbbbbbbbbbbbb`````aaaaaa",
"abbbbbbbbbbbbbbbbbbbbbb````aaaaa",
"aaabbbbbbbbbbbbbbbbbb```````aaaa",
"aaaaabbbbbbbbbbbbbb``````````aaa",
"aaaaaaabbbbbbbbbb`````````````aa",
"aaaaaaaaabbbbbba```````aaaaaaaaa",
"aaaaaaaaaaabbaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa",
"aaaaaaaabbbbbbbaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"baaaabbbbbbbbbbbbbaaaaaaaaaaaaaa"
};

#endif

char ** ppzbCustomIconXPM = apzbCustomIconXPM;


/* The Pantone logo in the About Dialog Box. */

/* XPM */
static char *apzbPantoneXPM[] = {
"100 90 3 1",
"` c black   m black  s  dark_color",
"a c white   m white  s  light_color",
"b c #d90000 m black  s  dark_color",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbabbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaabbbbbbbbbaaaaaabbbbaaaaabbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaabbbbbbbbbaaaabbbbbbbbbaaaabbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaabbbbbbbbbbaabbbbbbaaabbbbaaabbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaabbbbbbbbbbaaabbbaaaaaaaabbbaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaabbbbbbbbbbbaabbaaaaaaaaaaaabaaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaabbbbbbbbbbbaaabbaaaabbbbbaaabbaaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaabbbbbbbbbbbbaabbaaabbbbbbbbaabbbaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaabbbbbbbbbbbbbaabbaabbbbaaabbaabbbaabbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaabbbbbbbbbbbbbaaabbaabbbaaaaabbaabbaaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaabbbbbbbbbbbbbbaabbaabbbbaaaaabbaabbbaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaabbbbbbbbbbbbbbbaabbaabbbaaaaaaabaabbbaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaabbbbbbbbbbbbbbaabbaabbbaaaaaaabaabbbaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaabbbbbbbbbbbbbaaabbaabbbaaaaabbaabbaaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaabbbbbbbbbbbbbaabbaabbbbbabbbaabbbaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaabbbbbbbbbbbbaabbbaaabbbbbbaaabbaaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaabbbbbbbbbbbaaabbaaaaabbaaaaabbaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaabbbbbbbbbbbaabbbbaaaaaaaaabbaaabbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaabbbbbbbbbbaaaabbbbaaaaabbbaaabbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaabbbbbbbbbbaaaaabbbbabbbaaaabbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaabbbbbbbbbbbaaaaaabbbaaaaabbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaabbbbbbbbbbbbaaaaaaaaaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaabbbbbbbbbbbbbbaaaabbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbaaaaaa`````````````````````````````````aaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab`````````````````````````````````````````````````aaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`````````````````````````````````````````aaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa````````````````````````aaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa````````aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa````aaa``aa``aaa````````a```aa``aaa````````aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``a``aa``aa```aa``aa`aaa``aa`````aa````aaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``aa``````a````a``aa`aaa``aa``````a```````aaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa````aa``a`a``a`a``aa`aa``aaaa```a`a```````aaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``aaaa```````a````aa`aa``aaaa```a``````aaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``aaa``aa````aa```aa`aaa``a`````aa`````````aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``aaa``aaa```aaa``aa`aaaaa``aa``aaa````````aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa```aaaa``aa``aaa``````aa`````aaaa``a```````````a````aa``````a``aa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`````aaa``aa``aaa```````a``````aaa``a```````````a`````a``````a``aa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`aaa``a````a``aaa````aa````aa``aa````aa``aa``aaaa``aa`aa``a`````aa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``aaaaaa`a``a``aaa```````a`````aaa`a``aa``aa`````a``aa``a``a`````aa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``aaa```````a``aaa```````a`````aa`````aa``aa`````a``a```a``a`a```aa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``a``a`````a``aaa````aa````aa``a`````aa``aa``aaaa``a``aaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa````a```a```````````````a``aa`````a```a``aa`````a`````aaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`aa``aaa`````````````aa``aaa```aaa``a``aa`````a```aaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
};


char ** ppzbPantoneXPM = apzbPantoneXPM;



/* The RSA logo in the About Dialog Box. */

/* XPM */
static char *apzbRSAXPM[] = {
"50 49 48 2",
"`` c #fbd27c  m black  s  dark_color",
"`a c #cf5258 m black  s  dark_color",
"`b c #d66d72 m black  s  dark_color",
"`c c #fdefd3 m black  s  dark_color",
"`d c #fecb00 m black  s  dark_color",
"`e c #f7e3e4 m black  s  dark_color",
"`f c #e8aeb1 m black  s  dark_color",
"`g c #ced7e3 m black  s  dark_color",
"`h c #e5a1a4 m black  s  dark_color",
"`i c #dee4ec m black  s  dark_color",
"`j c #eef1f5 m black  s  dark_color",
"`k c #c8373f m black  s  dark_color",
"`l c #fefefe m white  s  light_color",
"`m c #efc9cb m black  s  dark_color",
"`n c #fdebc8 m black  s  dark_color",
"`o c #7e97b5 m black  s  dark_color",
"`p c #fce8bd m black  s  dark_color",
"`q c #8ea4be m black  s  dark_color",
"`r c #9eb1c7 m black  s  dark_color",
"`s c #3f6491 m black  s  dark_color",
"`t c #4f719a m black  s  dark_color",
"`u c #fefaf3 m black  s  dark_color",
"`v c #fdf7e8 m black  s  dark_color",
"`w c #00316d m black  s  dark_color",
"`x c #fce4b2 m black  s  dark_color",
"`y c #fbce72 m black  s  dark_color",
"`z c #fdf3dd m black  s  dark_color",
"`{ c #d35f65 m black  s  dark_color",
"`| c #fce0a7 m black  s  dark_color",
"`} c #c42a32 m black  s  dark_color",
"`~ c #faf1f1 m black  s  dark_color",
"a` c #fbca67 m black  s  dark_color",
"aa c #dd878c m black  s  dark_color",
"ab c #aebed1 m black  s  dark_color",
"ac c #fac75c m black  s  dark_color",
"ad c #becbda m black  s  dark_color",
"ae c #da7a7f m black  s  dark_color",
"af c #cb454c m black  s  dark_color",
"ag c #5f7ea4 m black  s  dark_color",
"ah c #6f8bad m black  s  dark_color",
"ai c #fcd992 m black  s  dark_color",
"aj c #ecbbbe m black  s  dark_color",
"ak c #fbd687 m black  s  dark_color",
"al c #0f3e76 m black  s  dark_color",
"am c #1f4b7f m black  s  dark_color",
"an c #2f5888 m black  s  dark_color",
"ao c #f3d6d8 m black  s  dark_color",
"ap c #e19498 m black  s  dark_color",
"`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`w`w`w`w`w`wam`o`l`l`l`oam`w`w`walag`j`l`l`l`lah`w`w`w`janam`tah`w",
"`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`w`wal`san`w`w`w`r`l`r`w`wal`tam`w`wah`l`l`l`lam`w`w`w`rad`o`oal`w",
"`l`l`l`l`l`l`l`l`l`l`l`l`eaeaa`l`l`w`w`s`l`lah`w`w`o`l`s`w`wab`l`j`w`w`s`l`l`l`g`w`wal`wag`g`r`r`sah",
"`l`l`l`l`l`l`l`l`l`l`lapafaj`l`l`l`w`w`s`l`lad`w`w`o`l`s`w`wad`l`l`w`w`s`l`l`l`q`wam`t`wam`l`l`l`l`l",
"`l`l`l`l`l`l`l`l`lao`aae`~`l`l`l`l`w`w`s`l`lab`w`w`o`lag`w`wan`j`l`l`l`l`l`l`lan`wag`q`w`w`g`l`l`l`l",
"`l`l`l`l`l`l`l`laj`k`f`l`l`l`l`l`l`w`w`s`l`lah`w`w`r`l`jal`w`wan`i`l`l`l`l`l`i`w`w`r`g`w`w`q`l`l`l`l",
"`l`l`l`l`l`l`l`f`kao`l`l`l`l`l`l`l`w`wal`sal`w`wah`l`l`l`gam`w`walad`l`l`l`l`r`w`w`i`lal`w`s`l`l`l`l",
"`l`l`l`l`l`l`f`kao`l`l`l`l`l`l`l`l`w`w`w`w`w`w`w`s`j`l`l`l`j`t`w`w`w`r`l`l`l`t`wam`l`l`t`w`w`j`l`l`l",
"`l`l`l`l`laj`}`m`l`l`l`l`l`l`l`l`l`w`w`s`l`j`t`w`w`q`l`l`l`l`l`q`w`w`wab`l`j`w`w`sadadag`w`wab`l`l`l",
"`l`l`l`l`e`k`h`l`l`l`l`l`l`l`l`l`l`w`w`s`l`l`o`w`w`o`l`gadad`j`l`r`w`wan`lab`w`w`w`w`w`w`w`wag`l`l`l",
"`l`l`l`l`a`{`l`l`l`l`l`l`l`l`l`l`l`w`w`s`l`l`o`w`w`o`l`s`w`wad`l`lam`w`w`lag`w`w`o`o`o`oal`wam`l`l`l",
"`l`l`l`h`}`e`l`l`l`l`l`l`l`l`l`l`l`w`w`s`l`l`o`w`w`o`l`s`w`wab`l`jal`wan`lal`wam`l`l`l`l`s`w`w`g`l`l",
"`l`l`~`kap`v`|`|`|`|`|`|`|`|`c`l`l`w`w`s`l`l`o`w`w`o`lag`w`walagam`w`w`o`g`w`wag`l`l`l`l`o`w`w`q`l`l",
"`l`lap`k`~a``d`d`d`d`d`d`d`dac`l`l`w`w`s`l`l`r`w`w`o`l`jagal`w`w`wal`o`lah`w`w`r`l`l`l`lad`w`w`s`l`l",
"`l`~`kaa`l`d`d`d`d`d`d`d`d`d`d`x`v`l`l`l`l`l`l`l`l`l`l`l`l`l`jad`j`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l",
"`l`f`}ao`l`d`d`d`d`d`d`d`d`d`d`d`|`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l",
"`l`aaf`l`l`d`d`d`d`d`d`d`d`d`d`d```|`|`|`|`|`|`|`|`|`|`|`|`|`|`c`l`l`l`l`l`l`l`l`l`l`l`l`l`l`laa`e`l",
"`~`}aa`l`l`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`dac`z`l`l`l`l`l`l`l`l`l`l`l`l`l`l`h`h`l",
"`f`}aj`l`l`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`dac`v`l`lak`d`d`d`d`d`d`d`dak`l`m`b`l",
"aa`}`e`l`l`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`dai`l`l`l`d`d`d`d`d`d`d`d`d`d`l`l`k`l",
"`{`}`l`l`l`d`d`d`d`d`d`d`d`d`d`d`d`d`d`y`n`y`d```v`l`u```d`d`dai`l`l`z```d`d`d`d`d`d`d`d`d`d`l`l`k`~",
"af`a`l`l`l`d`d`d`d`d`d`d`d`d`d`d```|`x`l`l`l`c`l`l`l`l`l`x`|`x`l`l`l`c`d`d`d`d`d`d`d`d`d`d`d`l`l`{`m",
"`}`{`l`l`l`d`d`d`d`d`d`d`d`d`d`d`|`l`l`zak`z`l`nac`d`d`x`l`l`l`x`````y`d`d`d`d`d`d`d`d`d`d`d`l`l`{`m",
"`}`{`l`l`l`d`d`d`d`d`d`d`d`d`dai`c`l`zac`d`d```d`d`d`d`d```|ak`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`l`l`{`m",
"`}`{`l`l`lac`d`d`d`d`d`d`d`d`d`u`l`p`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`l`l`{`m",
"`}af`l`l`l`n`````````````````p`l`l`p`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`l`laf`m",
"`}`}`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`p`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`d`l`l`}`m",
"af`}`e`l`l`l`l`l`lad`o`r`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`c`d`d`d`d`d`d`d`d`d`d`d`lao`}ao",
"`{`}`f`l`l`l`i`jad`w`w`w`q`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`zac`d`d`d`d`d`d`d`d`d`d`l`f`}`l",
"aa`}ae`l`l`r`w`rah`w`o`tam`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`d`d`d`d`d`d`d`d`d`d`lae`a`l",
"aj`}af`l`l`salab`s`w`ial`w`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`y`d`d`d`d`d`d`d`d```l`kae`l",
"`~`}`}`m`lagamab`wam`jal`q`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`laj`}aj`l",
"`l`b`}ae`lad`w`w`wah`l`l`lagag`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`ran`l`l`l`l`l`l`l`l`l`{`k`l`l",
"`l`f`}`}`e`lad`o`r`l`l`lag`w`wag`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`r`wag`l`l`l`l`l`l`l`lao`}ae`l`l",
"`l`l`k`}ae`l`l`l`l`l`lag`wanag`wah`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`o`w`s`l`r`r`l`l`l`l`l`l`{`}ao`l`l",
"`l`lap`}`}`m`l`l`l`lag`w`w`q`lah`r`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`g`w`wag`wan`l`l`l`l`laj`}`{`l`l`l",
"`l`l`~`k`}af`~`l`lag`wanag`wab`l`jan`wamab`l`l`l`l`l`l`l`labag`wan`j`r`w`w`t`l`j`r`l`l`~`k`}ao`l`l`l",
"`l`l`laj`}`}ae`l`ial`w`i`lah`g`lag`w`tan`w`lad`o`i`i`oad`o`waman`w`q`l`r`waladan`w`g`l`b`}aa`l`l`l`l",
"`l`l`l`l`b`}`}`f`l`galan`j`l`l`i`wam`l`s`w`l`o`wadad`w`o`g`w`s`j`wah`l`l`r`w`wal`r`laa`}af`~`l`l`l`l",
"`l`l`l`l`~af`}`}`f`l`galab`l`lag`w`r`l`i`r`l`t`w`lad`w`o`lan`w`s`w`s`g`l`l`oal`g`l`f`}`}ao`l`l`l`l`l",
"`l`l`l`l`lao`k`}`}`f`l`l`l`l`lamal`j`l`l`l`l`s`w`lad`w`o`l`r`wal`t`wag`l`l`l`i`lap`}`}`f`l`l`l`l`l`l",
"`l`l`l`l`l`lao`}`}`}aa`l`l`l`l`wan`ial`q`l`l`s`w`lad`w`o`l`j`wam`lam`w`i`l`l`~ae`}`}`f`l`l`l`l`l`l`l",
"`l`l`l`l`l`l`lao`k`}`}`aao`l`lah`w`w`w`q`l`l`s`w`lad`w`o`l`lag`wab`oamad`lao`a`}`}`f`l`l`l`l`l`l`l`l",
"`l`l`l`l`l`l`l`laoaf`}`}`}ap`~`lad`o`r`l`l`lag`wah`s`wab`l`ladal`r`l`l`~ae`}`}`k`f`l`l`l`l`l`l`l`l`l",
"`l`l`l`l`l`l`l`l`l`~`b`}`}`}`kap`e`l`l`l`l`l`j`s`w`wah`l`l`l`l`l`l`eaa`k`}`}`aao`l`l`l`l`l`l`l`l`l`l",
"`l`l`l`l`l`l`l`l`l`l`lajaf`}`}`}`}`b`f`e`l`l`l`l`l`l`l`l`l`lao`h`a`}`}`}`kap`l`l`l`l`l`l`l`l`l`l`l`l",
"`l`l`l`l`l`l`l`l`l`l`l`l`~ap`k`}`}`}`}`}`k`{aaapapapapae`{`k`}`}`}`}`kap`~`l`l`l`l`l`l`l`l`l`l`l`l`l",
"`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`f`b`}`}`}`}`}`}`}`}`}`}`}`}`}`}`}`a`h`~`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l",
"`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`~ajap`{af`}`}`}`}`}af`{aa`f`e`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l`l"
};


char ** ppzbRSAXPM = apzbRSAXPM;


char ** ppzbHqnAtHeartXPM = NULL;


