/* $HopeName: HQNlibopenssl!unix:src:buildinf.h(EBDSDK_P.1) $ */
#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "gcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_NO_KRB5 -DOPENSSL_NO_ASM -DOPENSSL_NO_HW -DOPENSSL_NO_ENGINE -DL_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -mcpu=pentium -Wall"
  #define PLATFORM "linux-pentium"
  #define DATE "Mon Apr 25 12:07:57 BST 2005"
#endif
